name := "Projet_SDA"
version := "1.0"
scalaVersion := "2.12.15"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.3.1"
libraryDependencies += "com.beust" % "jcommander" % "1.48"
libraryDependencies += "com.typesafe.play" %% "play-json" % "2.9.4"
libraryDependencies += "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.13.5"
libraryDependencies += "com.databricks" %% "spark-xml" % "0.15.0"